apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tksimejicom-ingress
spec:
  rules:
    - host: tksimeji.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tksimejicom-service
                port:
                  number: 80