apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tksimejicom-ingress
spec:
  tls:
    - hosts:
        - tksimeji.com
      secretName: tksimejicom-tls
  rules:
    - host: tksimeji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tksimejicom-service
                port:
                  number: 80